create bootstrap script

diff --git a/misc/bootstrap b/misc/bootstrap
--- a/misc/bootstrap
+++ b/misc/bootstrap
@@ -1,39 +1,70 @@
 #!/bin/bash
 
 set -euf -o pipefail
+trap 'pid=$(jobs -p); if test "$pid"; then kill $pid; fi' EXIT
 
-# create devbox
+# check for existing etcd
 
-./datingnode-local resource create \
-	--update-existing \
-	--class "vagrant-devbox" \
-	--name "datingnode-devbox" \
-	--set "private.address" "172.28.128.5"
+if test -f /etc/init/etcd.conf; then
+	echo "Etcd already seems to be installed, aborting..." >&2
+	exit 1
+fi
 
-# create containers
+# download etcd
 
-./datingnode-local resource create \
-	--update-existing \
-	--class "database-master" \
-	--name "database-master-0" \
-	--parent "datingnode-devbox"
+cd /tmp
+if ! test -f etcd-v2.0.11-linux-amd64.tar.gz; then
+	echo "Downloading etcd" >&2
+	curl -# -L https://github.com/coreos/etcd/releases/download/v2.0.11/etcd-v2.0.11-linux-amd64.tar.gz -o etcd-v2.0.11-linux-amd64.tar.gz
+fi
 
-./datingnode-local resource create \
-	--update-existing \
-	--class "web-application" \
-	--name "web-application-0" \
-	--parent "datingnode-devbox"
+echo "Extracting etcd" >&2
+rm -rf etcd-v2.0.11-linux-amd64
+tar xzf etcd-v2.0.11-linux-amd64.tar.gz
+cd etcd-v2.0.11-linux-amd64
 
-./datingnode-local resource create \
-	--update-existing \
-	--class "vhost-proxy" \
-	--name "vhost-proxy-0" \
-	--parent "datingnode-devbox"
+echo "Starting temporary etcd" >&2
+./etcd &>/tmp/etcd.log &
+etcd_pid=$!
 
-./datingnode-local resource create \
-	--update-existing \
-	--class "memcache" \
-	--name "memcache-0" \
-	--parent "datingnode-devbox"
+echo "Started as PID $etcd_pid" >&2
+sleep 1
 
-# ex: noet ts=4 filetype=sh
+echo "Configuring temporary connection" >&2
+cd ~/datingnode-ansible
+cat >config/connections.yml <<-EOF
+	---
+	datingnode-local:
+	  etcd_servers: [ "localhost" ]
+	  etcd_secure: "no"
+	  etcd_prefix: "/datingnode-local"
+EOF
+
+echo "Initialising resources" >&2
+misc/create-resources
+
+echo "Configuring devbox" >&2
+./datingnode-local ansible playbook -- playbooks/vagrant-devbox.yml
+
+echo "Exporting data from etcd" >&2
+./datingnode-local etcd export --target work/etcd-bootstrap
+
+echo "Killing temporary etcd" >&2
+kill $etcd_pid
+sleep 2
+
+echo "Configuring permanent connection" >&2
+cat >config/connections.yml <<-EOF
+	---
+	datingnode-local:
+	  etcd_servers: [ "datingnode-devbox" ]
+	  etcd_secure: "no"
+	  etcd_prefix: "/datingnode-local"
+EOF
+
+echo "Importing data to etcd" >&2
+./datingnode-local etcd import --source work/etcd-bootstrap
+
+echo "Bootstrap complete" >&2
+
+# ex: noet ts=4 filetype=yaml
